### ISSUE TITLE
how do i get the auto recorded demo out of the container?

### ISSUE THREAD

**Issue by BabyFoxy** [timche/docker-csgo#16]
I have enabled record=1:1 in PUGSETUP_SETUPOPTIONS, just wondering, how I can get the demo out from the container when the recording is finished? TIA

**Comment by timche** [comment]
The demo file is stored in the `/home/csgo/server` bound volume. If you need access to the volume, you should use bind mounts: https://docs.docker.com/storage/bind-mounts/ so the volume is a directory in e.g. your home folder.

**Comment by BabyFoxy** [comment]
I was able to mount the volume, however, after waiting for the updating, I have got an error msg said could not be written due to permission, any idea what went wrong? I was mount with RW permission already
