### ISSUE TITLE
How to input csgo commands to server through the image

### ISSUE THREAD

**Issue by michihupf** [timche/docker-csgo#19]
Is there a way to input commands through the server console via the image? 
Just typing it in when attached is not working.

**Comment by timche** [comment]
Unfortunately you can't. What are you trying to do? 

Attaching to the process directly is risky as you could accidentally shutdown to the server if you are not exiting from the process correctly. My advice would be to use an RCON client instead like https://github.com/gorcon/rcon-cli if you want to execute commands on the server.

**Comment by michihupf** [comment]
Seems like a good point. I will use an RCON client. Thanks for the client suggestion.
