### ISSUE TITLE
Container fails during startup

### ISSUE THREAD

**Issue by josephhu-personal** [timche/docker-csgo#32]
> Starting server ...
+ exec /home/csgo/server/srcds_run -game csgo -console -norestart -usercon -nobreakpad +ip 0.0.0.0 -port 27015 -tickrate 128 -maxplayers_override 16 +game_type 0 +game_mode 1 +mapgroup mg_active +map de_dust2 +rcon_password REDACTED +sv_setsteamaccount REDACTED 
/home/csgo/server/srcds_run: 32: /home/csgo/server/srcds_run: pushd: not found
/home/csgo/server/srcds_run: 35: /home/csgo/server/srcds_run: popd: not found
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/home/csgo/.steam/sdk32/steamclient.so
with error:
/home/csgo/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/csgo/.steam/sdk32/steamclient.so

**Comment by timche** [comment]
Unfortunately I'm unable to reproduce this issue with:

```
$ docker run \
  -v=csgo:/home/csgo/server \
  --net=host \
  timche/csgo
```

Please make sure you've enough disk space and use the latest Docker image.
