### ISSUE TITLE
Re-enable bots

### ISSUE THREAD

**Issue by janstuemmel** [timche/docker-csgo#33]
When disabling bots via `CSGO_DISABLE_BOTS=true` bot files get completly removed by the startup script:

https://github.com/timche/docker-csgo/blob/6305d5f3c46f08a2c8960d70ef3712726104267a/base/server.sh#L78-L90

It's impossible to re-enable bots again, but it would be possible when the script just renames the botfiles...

**Comment by timche** [comment]
Thanks for your suggestion! Will change this 👍

**Comment by timche** [comment]
Released in Released in https://github.com/timche/docker-csgo/releases/tag/4.0.0
