### ISSUE TITLE
Remove custom files from server directoy that are not present 

### ISSUE THREAD

**Issue by janstuemmel** [timche/docker-csgo#34]
Removed custom files are not removed from server directory. This cannot be done with rsync. Maybe soft links via `ln -s` would work...

https://github.com/timche/docker-csgo/blob/6305d5f3c46f08a2c8960d70ef3712726104267a/base/server.sh#L43

**Comment by timche** [comment]
Even using soft links wouldn't solve the issue entirely. Soft links that point to deleted files are then broken and would also break the server. But will look into it.

**Comment by timche** [comment]
Released in https://github.com/timche/docker-csgo/releases/tag/4.0.0

**Comment by janstuemmel** [comment]
nice. i wanted to look into overlay fs but this looks very cool. thank's a lot. 

ps: we had lot's of fun with your server on our yearly lanparty. works great...
