### ISSUE TITLE
Documentation request: how to start csgo-practice-mode 

### ISSUE THREAD

**Issue by Amyantis** [timche/docker-csgo#4]
Hello,

Thank you for developing those Docker images, it's really helpful.

I am able to run _timche/csgo:pug-practice_ image and to connect the server. I didn't configure anything else than:
```
docker run \
  -v=csgo:/home/csgo/server \
  --net=host \
  timche/csgo
```
From there, I would like to know how to start _csgo-practice-mode_. I suppose that I have to either enter commands in the server terminal or change some configuration but I didn't find how. I tried to run `.setup` in a client console, but the command was not found.

Could you add some documentation about how to use _csgo-practice-mode_ running your image?

Thank you!

**Comment by timche** [comment]
Thanks for reaching out @Amyantis.

You just need to follow step 3 of the installation guide of csgo-practice-mode: https://github.com/splewis/csgo-practice-mode#installation

In order to edit the required files, you can create these files in your [custom configs dir](https://github.com/timche/docker-csgo#populate-with-own-configs-and-maps) and they will be populated at the next container start.

Let me know if I could help you.

**Comment by Ditscheridou** [comment]
@timche i tried the required steps but it seems not to work. Added my custom config volume under /home/user/csgo:/var/csgo with the file addons/sourcemod/configs/admin_overrides.cfg and the content: 

Overrides
{
	"sm_practicemap"	""
	"sm_prac"		""
}

But when i type .setup in the chat nothing happens

**Comment by timche** [comment]
@Ditscheridou the images have changed. Are you using `timche/csgo:pug-practice`? If yes, did you restart the container in order to sync the configs?

**Comment by Ditscheridou** [comment]
yeah i did that, the files are shown in the container in /var/csgo, but the commands still dont work on the server itself

**Comment by timche** [comment]
Can you please share your container log before the server starts?

**Comment by timche** [comment]
@Ditscheridou I've released a new major version: https://github.com/timche/docker-csgo/releases/tag/1.0.0 

Please try again and open a new issue if you still have issues. Also check your csgo volume if the files are correct.
