### ISSUE TITLE
Cant launch Practice mode

### ISSUE THREAD

**Issue by Ditscheridou** [timche/docker-csgo#8]
Hi, 

i currently struggeling to get the practice mode to work. Its greyed out in the setup menu. I followed the [wiki](https://github.com/splewis/csgo-practice-mode/wiki/Command-access) and checked the file in /addons/sourcemod/configs. Its set to: 

Overrides
{
        "sm_practicemap"        ""
        "sm_prac"               ""
}

So everyone can do everything there. Even i tried to set me as the owner and changing this to use the "g" command it didnt worked. It seems like the server is ignoring this file. 
I created the container with following commands: 

docker run --name=PUG_SERVER_2 -v="csgo:/home/csgo/server" -e CSGO_GSLT=MYTOKEN -e CSGO_MAX_PLAYER=12 -e CSGO_RCON_PW=Serverpw -e CSGO_PW=serverpw -e CSGO_GAME_TYPE=0 -e CSGO_GAME_MODE=1 -e CSGO_FORCE_NETSETTINGS=true -e CSGO_DISABLE_BOTS=false -e CSGO_HOSTNAME=gameservername -e CSGO_MAP=de_mirage -e CSGO_PORT=27016 -e CSGO_TV_ENABLE=true --net=host -d timche/csgo:pug-practice-2.3.1

(masked the sensitive parts here)

Any help will be appreciated im currently a little bit desperated :D

**Comment by timche** [comment]
Where did you change `addons/sourcemod/configs/admin_overrides.cfg`?

**Comment by Ditscheridou** [comment]
okay i just reviewed it and saw the error. when doing -v /home/didi/custom-files:/usr/csgo, the overwritten admin config are not present in the container. currently not sure why.

**Comment by timche** [comment]
Check your container logs for `> Checking for custom files at /usr/csgo ...` and `> Found custom files, applying ...` and see if the file is logged below that.

**Comment by Ditscheridou** [comment]
solved it. your first question guides me to my mistake, i didnt created the custom-files directory in correct manner

**Comment by timche** [comment]
Great to hear! Hope you like the image!
