### ISSUE TITLE
I installed this on my Synology NAS, the bots are frozen

### ISSUE THREAD

**Issue by ebdrup** [timche/docker-csgo#9]
Thanks a LOT for making this image available! It's great.
The server works after updating itself. But all the bots do not move - how do I get them to move?
I'm very new to cs:go (Played it 4 times now) 

I've attached the server log. I restarted the server once.
[timche-csgo1.csv.txt](https://github.com/timche/docker-csgo/files/5899551/timche-csgo1.csv.txt)

**Comment by horviskoadrianko** [comment]
After new update that removed bots in competetive the bots wont move and they stay in spawn. You need to set it to deathmatch or other mode than competetive or wingman.

**Comment by ebdrup** [comment]
Thanks!
